"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#gsc6qh&%i5j!l+6zrxdx@q8h5=soqa400ec(s+s!$w8r68y72'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webhotroxuongBB',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR  / "webhotroxuongBB" / 'templates'],   
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'erp',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.10.33',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
        },
    },
    '33BB': {
        'ENGINE': 'mssql',
        'NAME': 'BB',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.10.33',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB1': {
        'ENGINE': 'mssql',
        'NAME': 'mfns',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.21',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB2': {
        'ENGINE': 'mssql',
        'NAME': 'mfns',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.22',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',\
            'connection_timeout': 2,
        },
    },
    'BB3': {
        'ENGINE': 'mssql',
        'NAME': 'mfns',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.23',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB4': {
        'ENGINE': 'mssql',
        'NAME': 'mfns',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.24',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB5': {
        'ENGINE': 'mssql',
        'NAME': 'mfns',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.35',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB6': {
        'ENGINE': 'mssql',
        'NAME': 'mfns',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.36',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB7': {
        'ENGINE': 'mssql',
        'NAME': 'mfns',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.37',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB8': {
        'ENGINE': 'mssql',
        'NAME': 'mfns',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.38',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB1_mfnsshare': {
        'ENGINE': 'mssql',
        'NAME': 'mfnsShareDB',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.21',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB2_mfnsshare': {
        'ENGINE': 'mssql',
        'NAME': 'mfnsShareDB',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.22',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB3_mfnsshare': {
        'ENGINE': 'mssql',
        'NAME': 'mfnsShareDB',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.23',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB4_mfnsshare': {
        'ENGINE': 'mssql',
        'NAME': 'mfnsShareDB',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.24',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB5_mfnsshare': {
        'ENGINE': 'mssql',
        'NAME': 'mfnsShareDB',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.35',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB6_mfnsshare': {
        'ENGINE': 'mssql',
        'NAME': 'mfnsShareDB',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.36',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB7_mfnsshare': {
        'ENGINE': 'mssql',
        'NAME': 'mfnsShareDB',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.37',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'BB8_mfnsshare': {
        'ENGINE': 'mssql',
        'NAME': 'mfnsShareDB',
        'USER': 'kendakv2',
        'PASSWORD': 'kenda123',
        'HOST': '198.1.8.38',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
            'connection_timeout': 2,
        },
    },
    'KV2KD': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kverp',
        'USER': 'postgres',
        'PASSWORD': 'kenda',
        'HOST': '198.1.10.85',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=kvmes'
        },
    },
     'KV1KD': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kverp',
        'USER': 'postgres',
        'PASSWORD': 'kenda',
        'HOST': '198.1.1.92',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=kvmes'
        },
    }

    

}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
